//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeolaserApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int id { get; set; }
        public string cif { get; set; }
        public int nombre { get; set; }
        public string direccion { get; set; }
        public string poblacion { get; set; }
        public string provincia { get; set; }
        public string codPostal { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
    }
}
